### ISSUE TITLE
Crash when creating or joining a world with 18.2 update installed

### ISSUE THREAD

**Issue by SamhainJack** [binary404/MysticTools#15]
Hi, I'm having this problem when trying to create a new world or join a world with the new version for 1.18.2 installed. The world cannot be created or joined and I crash back to login with the following error: 

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 3/18/22, 10:10 PM
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: binary404/fx_lib/fx/effects/FXSource
	at binary404.mystictools.common.loot.effects.UniqueEffect.<clinit>(UniqueEffect.java:32) ~[mystictools-1.18.2-1.0.0-B1.jar%2384!/:1.18.2-1.0.0-B1] {re:classloading}
	at binary404.mystictools.common.loot.LootItemHelper.getRandomUnique(LootItemHelper.java:319) ~[mystictools-1.18.2-1.0.0-B1.jar%2384!/:1.18.2-1.0.0-B1] {re:classloading}
	at binary404.mystictools.common.core.UniqueHandler.generateUniqueItems(UniqueHandler.java:26) ~[mystictools-1.18.2-1.0.0-B1.jar%2384!/:1.18.2-1.0.0-B1] {re:classloading}
	at binary404.mystictools.common.world.WorldHandler.worldLoad(WorldHandler.java:18) ~[mystictools-1.18.2-1.0.0-B1.jar%2384!/:1.18.2-1.0.0-B1] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_5_WorldHandler_worldLoad_Load.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:361) ~[client-1.18.2-20220228.144236-srg.jar%23105!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:316) ~[client-1.18.2-20220228.144236-srg.jar%23105!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.server.IntegratedServer.m_7038_(IntegratedServer.java:64) ~[client-1.18.2-20220228.144236-srg.jar%23105!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.18.2-20220228.144236-srg.jar%23105!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220228.144236-srg.jar%23105!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}
Caused by: java.lang.ClassNotFoundException: binary404.fx_lib.fx.effects.FXSource
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:134) ~[securejarhandler-1.0.3.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:134) ~[securejarhandler-1.0.3.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	... 14 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 712276992 bytes (679 MiB) / 2277507072 bytes (2172 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 8
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 3700U with Radeon Vega Mobile Gfx  
	Identifier: AuthenticAMD Family 23 Model 24 Stepping 1
	Microarchitecture: Zen / Zen+
	Frequency (GHz): 2.30
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: AMD Radeon(TM) RX Vega 10 Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 2048.00
	Graphics card #0 deviceId: 0x15d8
	Graphics card #0 versionInfo: DriverVersion=27.20.11044.5003
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 15051.33
	Virtual memory used (MB): 9344.00
	Swap memory total (MB): 4864.00
	Swap memory used (MB): 223.70
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	Server Running: true
	Player Count: 0 / 8; []
	Data Packs: vanilla, mod:radium (incompatible), mod:fullbrightnesstoggle, mod:magic_rings, mod:mystictools (incompatible), mod:cucumber, mod:trashslot (incompatible), mod:configmenusforge (incompatible), mod:jei (incompatible), mod:prefab (incompatible), mod:musicplayer, mod:sleeping_bags (incompatible), mod:waystones (incompatible), mod:journeymap, mod:citadel (incompatible), mod:alexsmobs (incompatible), mod:artifacts, mod:feature_nbt_deadlock_be_gone (incompatible), mod:betteranimalsplus (incompatible), mod:sophisticatedbackpacks (incompatible), mod:uteamcore, mod:balm (incompatible), mod:terralith, mod:fpsreducer (incompatible), mod:hidehands, mod:lucky (incompatible), mod:repurposed_structures, mod:terrablender (incompatible), mod:biomesoplenty (incompatible), mod:jade (incompatible), mod:forge (incompatible), mod:rapid_leaf_decay, mod:soupmod, mod:curios (incompatible), mod:reliquary (incompatible), mod:patchouli (incompatible), mod:randomite, mod:pamhc2foodcore, mod:croptopia (incompatible), mod:collective, mod:polymorph (incompatible), mod:autoreglib (incompatible), mod:quark (incompatible), mod:regrowth (incompatible), mod:inventoryprofilesnext (incompatible), mod:architectury (incompatible), mod:appleskin (incompatible), mod:aquaculture (incompatible), mod:expandability (incompatible), mod:convenientcurioscontainer (incompatible), mod:veinmining (incompatible), mod:geckolib3 (incompatible), mod:bettermodsbutton (incompatible), mod:cyclic, mod:defaultoptions (incompatible)
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	ModLauncher: 9.1.3+9.1.3+main.9b69c82a
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 slf4jfixer PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		radium-0.7.9.jar                                  |Radium                        |radium                        |0.7.9               |DONE      |Manifest: NOSIGNATURE
		fullbrightnesstoggle_1.18.2-1.4.jar               |Full Brightness Toggle        |fullbrightnesstoggle          |1.4                 |DONE      |Manifest: NOSIGNATURE
		Magic rings 4.0 1.18.2.jar                        |Magic rings                   |magic_rings                   |4.0                 |DONE      |Manifest: NOSIGNATURE
		mystictools-1.18.2-1.0.0-B1.jar                   |Mystic Tools                  |mystictools                   |1.18.2-1.0.0-B1     |DONE      |Manifest: NOSIGNATURE
		Cucumber-1.18.2-5.1.0.jar                         |Cucumber Library              |cucumber                      |5.1.0               |DONE      |Manifest: NOSIGNATURE
		trashslot-forge-1.18.1-11.0.2.jar                 |TrashSlot                     |trashslot                     |11.0.2              |DONE      |Manifest: NOSIGNATURE
		ConfigMenusForge-v3.2.0-1.18.2-Forge.jar          |Config Menus for Forge        |configmenusforge              |3.2.0               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		jei-1.18.2-9.5.3.143.jar                          |Just Enough Items             |jei                           |9.5.2.136           |DONE      |Manifest: NOSIGNATURE
		prefab-1.8.2.0.jar                                |Prefab                        |prefab                        |1.8.2.0             |DONE      |Manifest: NOSIGNATURE
		music_player-1.18.2-2.3.3.142.jar                 |Music Player                  |musicplayer                   |2.3.3.142           |DONE      |Manifest: f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
		sleeping_bags-1.18.2-1.0.1.jar                    |Sleeping Bags                 |sleeping_bags                 |1.18.2-1.0.1        |DONE      |Manifest: NOSIGNATURE
		waystones-forge-1.18.2-10.0.0.jar                 |Waystones                     |waystones                     |10.0.0              |DONE      |Manifest: NOSIGNATURE
		journeymap-1.18.2-5.8.0.jar                       |Journeymap                    |journeymap                    |5.8.0               |DONE      |Manifest: NOSIGNATURE
		citadel-1.11.1-1.18.2.jar                         |Citadel                       |citadel                       |1.11.1              |DONE      |Manifest: NOSIGNATURE
		alexsmobs-1.17.3.jar                              |Alex's Mobs                   |alexsmobs                     |1.17.3              |DONE      |Manifest: NOSIGNATURE
		artifacts-1.18.2-4.0.6.jar                        |Artifacts                     |artifacts                     |1.18.2-4.0.6        |DONE      |Manifest: NOSIGNATURE
		feature_nbt_deadlock_be_gone_forge-2.0.0+1.18.2.ja|Feature NBT Deadlock Be Gone  |feature_nbt_deadlock_be_gone  |2.0.0+1.18.2        |DONE      |Manifest: NOSIGNATURE
		betteranimalsplus-1.18.2-11.0.5-forge.jar         |Better Animals Plus           |betteranimalsplus             |1.18.2-11.0.5       |DONE      |Manifest: NOSIGNATURE
		sophisticatedbackpacks-1.18.2-3.15.17.559.jar     |Sophisticated Backpacks       |sophisticatedbackpacks        |1.18.2-3.15.17.559  |DONE      |Manifest: NOSIGNATURE
		u_team_core-1.18.2-4.0.0.204.jar                  |U Team Core                   |uteamcore                     |4.0.0.204           |DONE      |Manifest: f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
		balm-3.0.1+0.jar                                  |Balm                          |balm                          |3.0.1+0             |DONE      |Manifest: NOSIGNATURE
		Terralith_v2.2.1a.jar                             |Terralith                     |terralith                     |0.0NONE             |DONE      |Manifest: NOSIGNATURE
		FpsReducer-forge-1.25-mc1.18.jar                  |FPS Reducer                   |fpsreducer                    |1.25-mc1.18         |DONE      |Manifest: NOSIGNATURE
		hidehands_1.18.2-1.5.jar                          |Hide Hands                    |hidehands                     |1.5                 |DONE      |Manifest: NOSIGNATURE
		client-1.18.2-20220228.144236-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		lucky-block-forge-1.18.2-12.0.jar                 |Lucky Block                   |lucky                         |1.18.2-12.0         |DONE      |Manifest: NOSIGNATURE
		repurposed_structures_forge-5.0.4+1.18.2.jar      |Repurposed Structures         |repurposed_structures         |5.0.4+1.18.2        |DONE      |Manifest: NOSIGNATURE
		TerraBlender-forge-1.18.2-1.1.0.93.jar            |TerraBlender                  |terrablender                  |1.18.2-1.1.0.93     |DONE      |Manifest: NOSIGNATURE
		BiomesOPlenty-1.18.2-16.0.0.107-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.18.2-16.0.0.107   |DONE      |Manifest: NOSIGNATURE
		Jade-1.18.2-5.0.1.jar                             |Jade                          |jade                          |5.0.1               |DONE      |Manifest: NOSIGNATURE
		forge-1.18.2-40.0.19-universal.jar                |Forge                         |forge                         |40.0.19             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		RapidLeafDecay-1.18.2-2.0.0.jar                   |Rapid Leaf Decay              |rapid_leaf_decay              |2.0.0               |DONE      |Manifest: NOSIGNATURE
		soupcraft_1.1.3.jar                               |Soupmod                       |soupmod                       |1.1.3               |DONE      |Manifest: NOSIGNATURE
		curios-forge-1.18.2-5.0.6.3.jar                   |Curios API                    |curios                        |1.18.2-5.0.6.3      |DONE      |Manifest: NOSIGNATURE
		reliquary-1.18.2-2.0.1.1129.jar                   |Reliquary                     |reliquary                     |1.18.2-2.0.1.1129   |DONE      |Manifest: NOSIGNATURE
		Patchouli-1.18.2-66.jar                           |Patchouli                     |patchouli                     |1.18.2-66           |DONE      |Manifest: NOSIGNATURE
		randomite-1.18.2-1.1.2.jar                        |Randomite Classic             |randomite                     |1.1.2               |DONE      |Manifest: NOSIGNATURE
		pamhc2foodcore-1.18.2-1.0.0.jar                   |Pam's HarvestCraft 2 - Food Co|pamhc2foodcore                |1.0                 |DONE      |Manifest: NOSIGNATURE
		Croptopia-1.18.2-FORGE-1.8.2.jar                  |Croptopia                     |croptopia                     |1.8.2               |DONE      |Manifest: NOSIGNATURE
		collective-1.18.2-4.25.jar                        |Collective                    |collective                    |4.25                |DONE      |Manifest: NOSIGNATURE
		polymorph-forge-1.18.1-0.40.jar                   |Polymorph                     |polymorph                     |1.18.1-0.40         |DONE      |Manifest: NOSIGNATURE
		AutoRegLib-1.7-53.jar                             |AutoRegLib                    |autoreglib                    |1.7-53              |DONE      |Manifest: NOSIGNATURE
		Quark-3.2-344.jar                                 |Quark                         |quark                         |3.2-344             |DONE      |Manifest: NOSIGNATURE
		Regrowth-1.18.2-1.40.0.27.jar                     |Regrowth                      |regrowth                      |1.18.2-1.40.0.27    |DONE      |Manifest: NOSIGNATURE
		InventoryProfilesNext-forge-1.18.2-1.3.5.jar      |Inventory Profiles Next       |inventoryprofilesnext         |1.3.5               |DONE      |Manifest: NOSIGNATURE
		architectury-4.1.32.jar                           |Architectury                  |architectury                  |4.1.32              |DONE      |Manifest: NOSIGNATURE
		appleskin-forge-mc1.18-2.4.0.jar                  |AppleSkin                     |appleskin                     |2.4.0+mc1.18        |DONE      |Manifest: NOSIGNATURE
		Aquaculture-1.18.2-2.3.4.jar                      |Aquaculture 2                 |aquaculture                   |1.18.2-2.3.4        |DONE      |Manifest: NOSIGNATURE
		expandability-6.0.0.jar                           |ExpandAbility                 |expandability                 |6.0.0               |DONE      |Manifest: NOSIGNATURE
		convenientcurioscontainer-1.1-1.18.jar            |Convenient Curios Container   |convenientcurioscontainer     |1_forge-1.18        |DONE      |Manifest: NOSIGNATURE
		veinmining-forge-1.18.2-0.18.jar                  |Vein Mining                   |veinmining                    |1.18.2-0.18         |DONE      |Manifest: NOSIGNATURE
		geckolib-1.18-forge-3.0.12.jar                    |GeckoLib                      |geckolib3                     |3.0.12              |DONE      |Manifest: NOSIGNATURE
		BetterModsButton-v3.2.0-1.18.2-Forge.jar          |Better Mods Button            |bettermodsbutton              |3.2.0               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		Cyclic-1.18.2-1.6.17.jar                          |Cyclic                        |cyclic                        |1.18.2-1.6.17       |DONE      |Manifest: 1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
		defaultoptions-forge-1.18.1-14.1.0.jar            |Default Options               |defaultoptions                |14.1.0              |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: db593ad8-bb43-4239-839a-119468a4c855
	FML: 40.0
	Forge: net.minecraftforge:40.0.19

I hope this is the information you need. If you could help that would be grand! I love this mod.

**Comment by binary404** [comment]
I believe you can fix this by installing fx lib for now. A better fix will hopefully be coming out shortly.
